import type { RecommendationNarrativeView } from '@/types/renewal-case'

export function AiApprovalBriefPanel({
  narrative,
}: {
  narrative: RecommendationNarrativeView | null
}) {
  return (
    <div className="card">
      <h3 className="panel-title">AI Approval Brief</h3>

      {narrative ? (
        <>
          <div className="kv">
            <div className="muted">Generated By</div>
            <div>{narrative.modelLabel}</div>
          </div>

          <div style={{ marginTop: 16, whiteSpace: 'pre-wrap', lineHeight: 1.6 }}>
            {narrative.content}
          </div>
        </>
      ) : (
        <div className="empty-note">
          No approval brief has been generated for this case.
        </div>
      )}
    </div>
  )
}