import { FormattedAiText } from '@/components/ui/formatted-ai-text'
import type { RecommendationNarrativeView } from '@/types/renewal-case'

export function AiExecutiveSummaryPanel({
  narrative,
}: {
  narrative: RecommendationNarrativeView | null
}) {
  return (
    <div className="card">
      <h3 className="panel-title">AI Executive Summary</h3>

      {narrative ? (
        <>
          <div className="kv">
            <div className="muted">Generated By</div>
            <div>{narrative.modelLabel}</div>
          </div>

          <div style={{ marginTop: 16, whiteSpace: 'pre-wrap', lineHeight: 1.6 }}>
            <FormattedAiText text={narrative.content} />
          </div>
        </>
      ) : (
        <div className="empty-note">
          No AI executive summary has been generated yet.
        </div>
      )}
    </div>
  )
}
