import { labelize } from '@/lib/format/risk'

type RecalculationStatusPanelProps = {
  meta: {
    analysisVersion: number | null
    generatedBy: string | null
    updatedAtLabel: string | null
    approvalRequired: boolean
    drivers: string[]
  }
}

export function RecalculationStatusPanel({ meta }: RecalculationStatusPanelProps) {
  return (
    <div className="card">
      <details>
        <summary style={{ cursor: 'pointer', fontWeight: 600 }}>Analysis Metadata</summary>

        <div style={{ marginTop: 16 }}>
          <div className="kv">
            <div className="muted">Last Recalculated</div>
            <div>{meta.updatedAtLabel ?? 'Not available'}</div>
          </div>

          <div className="kv">
            <div className="muted">Analysis Version</div>
            <div>{meta.analysisVersion ?? '—'}</div>
          </div>

          <div className="kv">
            <div className="muted">Generated By</div>
            <div>{meta.generatedBy ? labelize(meta.generatedBy) : '—'}</div>
          </div>

          <div className="kv">
            <div className="muted">Approval Required</div>
            <div>{meta.approvalRequired ? 'Yes' : 'No'}</div>
          </div>

          <div style={{ marginTop: 16 }}>
            <div className="muted" style={{ marginBottom: 8 }}>
              Top Drivers
            </div>

            {meta.drivers.length > 0 ? (
              <ul style={{ margin: 0, paddingLeft: '1.25rem' }}>
                {meta.drivers.slice(0, 3).map((driver, index) => (
                  <li key={`${index}-${driver}`} style={{ marginBottom: 6 }}>
                    {driver}
                  </li>
                ))}
              </ul>
            ) : (
              <div>No drivers available.</div>
            )}
          </div>
        </div>
      </details>
    </div>
  )
}
