import { RecommendationNarrativeView } from '@/types/renewal-case'

export function RecommendationNarrativePanel({ narrative }: { narrative: RecommendationNarrativeView | null }) {
  return (
    <div className="card">
      <h3 className="panel-title">AI Rationale</h3>
      {narrative ? (
        <>
          <p style={{ marginTop: 0 }}>{narrative.content}</p>
          <div className="small muted">Generated by {narrative.modelLabel}</div>
        </>
      ) : (
        <p className="muted">No narrative available.</p>
      )}
    </div>
  )
}
